language: minimal
if: branch = v1.1beta

services:
  - docker

before_install:
- docker pull enterpriseconnect/webui:v1.1beta
- docker images

script:
- >
  docker run --network host
  -v $TRAVIS_BUILD_DIR:/build
  -it enterpriseconnect/webui:v1.1beta
  /bin/sh -c 'ls -al && npm install && npm test'

deploy:
  provider: pages 
  github_token: $GITHUB_TOKEN
  local_dir: .
  target_branch: gh-pages
  verbose: true
  skip_cleanup: true
  keep_history: true
  on:
    branch: v1.1beta
    
notifications:  
  email:  
    recipients:  
    - ec-research@ge.com
    - prasad.alokam@ge.com
    on_success: always  
    on_failure: always
