name: v1.1beta-ci
on:
  # Triggers the workflow on push or pull request events but only for the v1.1beta_helm_pkg_update_lber_ay branch
  push:
    branches: [ v1.1beta ]
  pull_request:
    branches: [ v1.1beta ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: v1.1beta
    #env:
     
    steps:
      - uses: actions/checkout@v2

      - name: bootstrap env
        id: bootstrap
        #env:
        run: |
          echo github.event = ${{ github.event }}
