name: v1.1beta-ci

on:
  push:
    branches:
      - [ v1.1beta ]
  pull_request:
    branches: [ v1.1beta ]
    types: [opened, synchronize]
  workflow_dispatch:  

jobs:
  test:
    name: v1.1beta-ci
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: ui-test
      run: docker run --network host -e CI=true -v $(pwd):/build enterpriseconnect/webui:v1.1beta /bin/sh -c 'ls -al && npm install && npm test'
