name: v1.1beta-ci

on:
  push:
    branches: [ v1.1beta ]
  pull_request:
    branches: [ v1.1beta ]
    types: [opened, synchronize]
  workflow_dispatch:  

jobs:
  test:
    name: Running Unit Cases
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    
    - name: Run Docker Command
      run: docker run --network host -v $(pwd):/build enterpriseconnect/webui:v1.1beta /bin/sh -c 'ls -al
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Run tests
      run: npm run test

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build

    - name: pr merged
      if: github.event_name == 'push'
      id: pr-merged
      run: |
          echo pr has been merged and closed
