name: v1.1beta-ci
on:
  push:
    branches: [ v1.1beta ]
  pull_request:
    branches: [ v1.1beta ]

  #workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: v1.1beta
    #env:
    steps:
      - uses: actions/checkout@v2
      - name: bootstrap env
        id: bootstrap
        #env:
        run: |
          echo github.event.pull_request = ${{ toJson(github.event.pull_request) }}
          echo github.event.push = ${{ toJson(github.event.push) }}
